todo:
- pct processing
- Map KD, REV, Sub ATT to int

ideas/notes:
- parse DETAILS column in fight data
    - can get judge scores and finish type
- add general parameterized load_if_exists function to utils to replace data loading functions in scrapers
- fighter stats with no data are recorded as "0" online, care
- derived fighter columns for
    - win streaks
    - ufc record
    - total record
    - champion/former champ status
- only pulling weight from fight data, not fighter data to account for people moving around divisions
    - would be nice to list all weights competed at/have missed weight marks, but weigh in weight isn't present on ufcstats
- reorg scraper class so that it makes more sense as a data entry point.

- including w/l/d/nc data for fighter biography, but take care using it
    - if used in training data, you really want their record at the time of the fight, not current
    - might be able to reverse engineer that from the fight data by counting their ufc fights, but this logic would mess up if there were gaps in someones ufc stint (eg fights in ufc, fights in other org, then fights back in ufc)

In [1]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

# IMMEDIATELY CHANGE TO ROOT DIR
# ONLY RUN THIS ONCE/INCLUDED CODE TO RESTART KERNEL ON EXECUTE.
# POSSIBLY ONLY USE THIS CONTEXT MANAGER
import os
os.chdir('..')
print(os.getcwd())

# local imports once you're in the root
from src.ufctools.scraping import FightDataScraper
from src.ufctools.preprocess import process_fighter_data, process_fight_data

d:\code\frankie_edgar_stan_zone

In [ ]:
scraper = FightDataScraper()
fight_df = scraper.fight_data
fighter_df = scraper.fighter_data

Pulling event data from http://ufcstats.com/statistics/events/completed?page=all
Reading local event data from d:\code\frankie_edgar_stan_zone\data\event_data.csv
No new events, local data up to date
Loading local fight links from d:\code\frankie_edgar_stan_zone\data\fight_links.pickle
Reading local raw fight data from d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Reading local raw fighter data from d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

In [3]:
# data scraped as of 11/20
scraper.scrape_new_fights()
scraper.update_fighter_data()

Checking for new events to scrape
Scraping fight links from 15 events:
Progress: |██████████████████████████████████████████████████| 100.00% Complete
Scraping fights from 15 event/s.

0it [00:00, ?it/s]

Updating fight data.
Saving fight data to d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Removing temporary files
Refreshing fighter data with fights from 2025-07-24 00:00:00 onwards.
Getting data for 356 fighters.

  0%|          | 0/356 [00:00<?, ?it/s]

Saving fighter data to d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

,FIGHTER_LINK,AS_OF_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
0f1efce7d2571d10,http://ufcstats.com/fighter-details/0f1efce7d2...,2025-11-20,NIKOLAY VERETENNIKOV,13,7,0,0,"6' 1""",170 LBS.,"74""",ORTHODOX,"DEC 22, 1989",2.49,56%,3.25,44%,0.43,16%,62%,0.4
d25240135aee03e5,http://ufcstats.com/fighter-details/d25240135a...,2025-11-20,TABATHA RICCI,12,3,0,0,"5' 1""",115 LBS.,"61""",ORTHODOX,"FEB 21, 1995",4.18,36%,5.19,57%,2.69,37%,78%,0.1
6d4b63c767106d3a,http://ufcstats.com/fighter-details/6d4b63c767...,2025-11-20,VICENTE LUQUE,23,12,1,0,"5' 11""",170 LBS.,"75""",ORTHODOX,"NOV 27, 1991",4.83,51%,5.30,51%,0.90,48%,60%,0.7
2c5f5749569eef66,http://ufcstats.com/fighter-details/2c5f574956...,2025-11-20,TAINARA LISBOA,7,4,0,0,"5' 7""",135 LBS.,"67""",ORTHODOX,"MAR 02, 1991",2.01,44%,2.88,45%,1.67,31%,53%,0.3
447f9858ae78f921,http://ufcstats.com/fighter-details/447f9858ae...,2025-11-20,MUSLIM SALIKHOV,22,6,0,0,"5' 11""",170 LBS.,"70""",ORTHODOX,"JUN 09, 1984",3.37,49%,2.96,62%,1.07,32%,72%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a20d7dfaba74c067,http://ufcstats.com/fighter-details/a20d7dfaba...,2025-11-20,RODRIGO DAMM,13,9,0,0,"5' 7""",155 LBS.,"71""",ORTHODOX,"FEB 03, 1980",3.5,36%,5.61,57%,0.44,16%,80%,0.3
31652c9267606d54,http://ufcstats.com/fighter-details/31652c9267...,2025-11-20,JOHN LOBER,5,9,4,0,"5' 11""",199 LBS.,--,ORTHODOX,"FEB 26, 1968",0.0,0%,0.0,0%,0.0,0%,0%,0.0
86f582852a5b240a,http://ufcstats.com/fighter-details/86f582852a...,2025-11-20,MAC DANZIG,21,12,1,0,"5' 8""",155 LBS.,"70""",ORTHODOX,"JAN 02, 1980",3.39,48%,3.44,57%,1.2,37%,46%,0.6
ff6a1f63c254127e,http://ufcstats.com/fighter-details/ff6a1f63c2...,2025-11-20,ALBERT TUMENOV,18,4,0,0,"5' 11""",170 LBS.,"73""",ORTHODOX,"DEC 26, 1991",3.76,42%,3.34,58%,0.2,20%,75%,0.0
51b1e2fd9872005b,http://ufcstats.com/fighter-details/51b1e2fd98...,2025-11-20,MACKENS SEMERZIER,8,4,0,1,"5' 9""",145 LBS.,"72""",ORTHODOX,"NOV 03, 1980",2.91,45%,3.48,46%,2.14,50%,50%,2.1

In [6]:
process_fighter_data(scraper.fighter_data)

Saving to d:\code\frankie_edgar_stan_zone\data\processed_fighter_details.csv

,FIGHTER_LINK,AS_OF_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
0f1efce7d2571d10,http://ufcstats.com/fighter-details/0f1efce7d2...,2025-11-20,NIKOLAY VERETENNIKOV,13,7,0,0,73,170,74,ORTHODOX,1989-12-22,2.49,0.56,3.25,0.44,0.43,0.16,0.62,0.4
d25240135aee03e5,http://ufcstats.com/fighter-details/d25240135a...,2025-11-20,TABATHA RICCI,12,3,0,0,61,115,61,ORTHODOX,1995-02-21,4.18,0.36,5.19,0.57,2.69,0.37,0.78,0.1
6d4b63c767106d3a,http://ufcstats.com/fighter-details/6d4b63c767...,2025-11-20,VICENTE LUQUE,23,12,1,0,71,170,75,ORTHODOX,1991-11-27,4.83,0.51,5.30,0.51,0.90,0.48,0.60,0.7
2c5f5749569eef66,http://ufcstats.com/fighter-details/2c5f574956...,2025-11-20,TAINARA LISBOA,7,4,0,0,67,135,67,ORTHODOX,1991-03-02,2.01,0.44,2.88,0.45,1.67,0.31,0.53,0.3
447f9858ae78f921,http://ufcstats.com/fighter-details/447f9858ae...,2025-11-20,MUSLIM SALIKHOV,22,6,0,0,71,170,70,ORTHODOX,1984-06-09,3.37,0.49,2.96,0.62,1.07,0.32,0.72,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a20d7dfaba74c067,http://ufcstats.com/fighter-details/a20d7dfaba...,2025-11-20,RODRIGO DAMM,13,9,0,0,67,155,71,ORTHODOX,1980-02-03,3.50,0.36,5.61,0.57,0.44,0.16,0.80,0.3
31652c9267606d54,http://ufcstats.com/fighter-details/31652c9267...,2025-11-20,JOHN LOBER,5,9,4,0,71,199,0,ORTHODOX,1968-02-26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
86f582852a5b240a,http://ufcstats.com/fighter-details/86f582852a...,2025-11-20,MAC DANZIG,21,12,1,0,68,155,70,ORTHODOX,1980-01-02,3.39,0.48,3.44,0.57,1.20,0.37,0.46,0.6
ff6a1f63c254127e,http://ufcstats.com/fighter-details/ff6a1f63c2...,2025-11-20,ALBERT TUMENOV,18,4,0,0,71,170,73,ORTHODOX,1991-12-26,3.76,0.42,3.34,0.58,0.20,0.20,0.75,0.0
51b1e2fd9872005b,http://ufcstats.com/fighter-details/51b1e2fd98...,2025-11-20,MACKENS SEMERZIER,8,4,0,1,69,145,72,ORTHODOX,1980-11-03,2.91,0.45,3.48,0.46,2.14,0.50,0.50,2.1

In [4]:
processed_fight_data = process_fight_data(fight_df, save_local = False)