todo:
- process control time
- pct processing
- Map KD, REV, Sub ATT to int

ideas/notes:
- parse DETAILS column in fight data
    - can get judge scores and finish type
- add general parameterized load_if_exists function to utils to replace data loading functions in scrapers
- fighter stats with no data are recorded as "0" online, care
- derived fighter columns for
    - win streaks
    - ufc record
    - total record
    - champion/former champ status
- only pulling weight from fight data, not fighter data to account for people moving around divisions
    - would be nice to list all weights competed at/have missed weight marks, but weigh in weight isn't present on ufcstats
- reorg scraper class so that it makes more sense as a data entry point.

- including w/l/d/nc data for fighter biography, but take care using it
    - if used in training data, you really want their record at the time of the fight, not current
    - might be able to reverse engineer that from the fight data by counting their ufc fights, but this logic would mess up if there were gaps in someones ufc stint (eg fights in ufc, fights in other org, then fights back in ufc)

In [1]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

# IMMEDIATELY CHANGE TO ROOT DIR
# ONLY RUN THIS ONCE/INCLUDED CODE TO RESTART KERNEL ON EXECUTE.
# POSSIBLY ONLY USE THIS CONTEXT MANAGER
import os
os.chdir('..')
print(os.getcwd())

# local imports once you're in the root
from src.ufctools.scraping import FightDataScraper
from src.ufctools.preprocess import process_fighter_data, process_fight_data

d:\code\frankie_edgar_stan_zone

In [2]:
scraper = FightDataScraper()

Pulling event data from http://ufcstats.com/statistics/events/completed?page=all
Reading local event data from d:\code\frankie_edgar_stan_zone\data\event_data.csv
No new events, local data up to date
Loading local fight links from d:\code\frankie_edgar_stan_zone\data\fight_links.pickle
Reading local raw fight data from d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Reading local fighter data from d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

In [3]:
# data scraped as of 7/08
scraper.scrape_new_fights()
scraper.update_fighter_data()

Checking for new events to scrape
Scraping fight links from 1 events:
Progress: |██████████████████████████████████████████████████| 100.00% Complete
Scraping fights from 1 event/s.

0it [00:00, ?it/s]

Updating fight data.
Saving fight data to d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Removing temporary files
Refreshing fighter data with fights from 2025-07-08 00:00:00 onwards.
Getting data for 24 fighters.

  0%|          | 0/24 [00:00<?, ?it/s]

Saving fighter data to d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

,FIGHTER_LINK,AS_OF_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
c15fa95b9a12fde4,http://ufcstats.com/fighter-details/c15fa95b9a...,2025-07-19,JUNIOR TAFA,6,4,0,0,"6' 3""",205 LBS.,"75""",ORTHODOX,"SEP 21, 1996",3.19,51%,2.49,51%,0.00,0%,69%,0.0
745fa7b605f8e2da,http://ufcstats.com/fighter-details/745fa7b605...,2025-07-19,FATIMA KLINE,8,1,0,0,"5' 6""",115 LBS.,"67""",ORTHODOX,"JUL 12, 2000",3.94,49%,2.29,59%,1.21,60%,50%,0.0
de594b35c45c2e9a,http://ufcstats.com/fighter-details/de594b35c4...,2025-07-19,EDUARDA MOURA,12,1,0,0,"5' 6""",125 LBS.,"67""",ORTHODOX,"FEB 28, 1994",3.04,37%,2.47,61%,3.73,37%,80%,0.3
8667caa0451d245b,http://ufcstats.com/fighter-details/8667caa045...,2025-07-19,KENNEDY NZECHUKWU,14,6,0,0,"6' 5""",236 LBS.,"83""",SOUTHPAW,"JUN 13, 1992",5.33,46%,4.89,51%,0.55,45%,80%,0.2
751de04455cfaac0,http://ufcstats.com/fighter-details/751de04455...,2025-07-19,CALVIN KATTAR,23,10,0,0,"5' 11""",145 LBS.,"72""",ORTHODOX,"MAR 26, 1988",4.41,37%,6.55,54%,0.34,29%,77%,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6add18754930182b,http://ufcstats.com/fighter-details/6add187549...,2025-07-19,JULIUS WALKER,6,1,0,0,"6' 4""",205 LBS.,"78""",ORTHODOX,"JUL 16, 1999",5.73,50%,5.8,40%,1.0,11%,100%,0.0
31652c9267606d54,http://ufcstats.com/fighter-details/31652c9267...,2025-07-19,JOHN LOBER,5,9,4,0,"5' 11""",199 LBS.,--,ORTHODOX,"FEB 26, 1968",0.0,0%,0.0,0%,0.0,0%,0%,0.0
86f582852a5b240a,http://ufcstats.com/fighter-details/86f582852a...,2025-07-19,MAC DANZIG,21,12,1,0,"5' 8""",155 LBS.,"70""",ORTHODOX,"JAN 02, 1980",3.39,48%,3.44,57%,1.2,37%,46%,0.6
ff6a1f63c254127e,http://ufcstats.com/fighter-details/ff6a1f63c2...,2025-07-19,ALBERT TUMENOV,18,4,0,0,"5' 11""",170 LBS.,"73""",ORTHODOX,"DEC 26, 1991",3.76,42%,3.34,58%,0.2,20%,75%,0.0
51b1e2fd9872005b,http://ufcstats.com/fighter-details/51b1e2fd98...,2025-07-19,MACKENS SEMERZIER,8,4,0,1,"5' 9""",145 LBS.,"72""",ORTHODOX,"NOV 03, 1980",2.91,45%,3.48,46%,2.14,50%,50%,2.1

In [3]:
fight_df = scraper.fight_data

In [4]:
test = process_fight_data(fight_df, save_local = False)

In [5]:
test

,FIGHT_LINK,R_FIGHTER,R_FIGHTER_ID,R_FIGHTER_LINK,R_FIGHTER_RESULT,B_FIGHTER,B_FIGHTER_ID,B_FIGHTER_LINK,B_FIGHTER_RESULT,METHOD,...,B_DISTANCE_R5_LANDED,B_DISTANCE_R5_ATTEMPTED,R_CLINCH_R5_LANDED,R_CLINCH_R5_ATTEMPTED,B_CLINCH_R5_LANDED,B_CLINCH_R5_ATTEMPTED,R_GROUND_R5_LANDED,R_GROUND_R5_ATTEMPTED,B_GROUND_R5_LANDED,B_GROUND_R5_ATTEMPTED
FIGHT_ID,,,,,,,,,,,,,,,,,,,,,
0adfc21045c02555,http://ufcstats.com/fight-details/0adfc21045c0...,DERRICK LEWIS,d3df1add9d9a7efb,http://ufcstats.com/fighter-details/d3df1add9d...,W,TALLISON TEIXEIRA,17923f676f100e16,http://ufcstats.com/fighter-details/17923f676f...,L,KO/TKO,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2a03bc4c491b4c9a,http://ufcstats.com/fight-details/2a03bc4c491b...,STEPHEN THOMPSON,4a28cb716c19157a,http://ufcstats.com/fighter-details/4a28cb716c...,L,GABRIEL BONFIM,01641ba5df0c69b0,http://ufcstats.com/fighter-details/01641ba5df...,W,DECISION - SPLIT,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
f368475c366c6d85,http://ufcstats.com/fight-details/f368475c366c...,CALVIN KATTAR,751de04455cfaac0,http://ufcstats.com/fighter-details/751de04455...,L,STEVE GARCIA,97cf1a2c7c5e7889,http://ufcstats.com/fighter-details/97cf1a2c7c...,W,DECISION - UNANIMOUS,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4e5d4a36eaaa3a78,http://ufcstats.com/fight-details/4e5d4a36eaaa...,NATE LANDWEHR,583ee11abddfc581,http://ufcstats.com/fighter-details/583ee11abd...,L,MORGAN CHARRIERE,5b03b61f9d90125e,http://ufcstats.com/fighter-details/5b03b61f9d...,W,KO/TKO,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4b75d3b7738cb278,http://ufcstats.com/fight-details/4b75d3b7738c...,VITOR PETRINO,71171fc96445bf65,http://ufcstats.com/fighter-details/71171fc964...,W,AUSTEN LANE,be9bdec19b7e9ffe,http://ufcstats.com/fighter-details/be9bdec19b...,L,SUBMISSION,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3b020d4914b44fc8,http://ufcstats.com/fight-details/3b020d4914b4...,ORLANDO WIET,a6c2f5381d575920,http://ufcstats.com/fighter-details/a6c2f5381d...,W,ROBERT LUCARELLI,96087e90d900f0ef,http://ufcstats.com/fighter-details/96087e90d9...,L,KO/TKO,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
d917c8c7461b9831,http://ufcstats.com/fight-details/d917c8c7461b...,FRANK HAMAKER,c3c23c99477c041b,http://ufcstats.com/fighter-details/c3c23c9947...,W,THADDEUS LUSTER,505934897b8b4824,http://ufcstats.com/fighter-details/505934897b...,L,SUBMISSION,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
ccee020be2e8d9f6,http://ufcstats.com/fight-details/ccee020be2e8...,JOHNNY RHODES,319fa1bd3176bded,http://ufcstats.com/fighter-details/319fa1bd31...,W,DAVID LEVICKI,49590e0508b2c19f,http://ufcstats.com/fighter-details/49590e0508...,L,KO/TKO,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4b9ae533ccb3fcdf,http://ufcstats.com/fight-details/4b9ae533ccb3...,PATRICK SMITH,46c8ec317aff28ac,http://ufcstats.com/fighter-details/46c8ec317a...,W,RAY WIZARD,ea0ad155451ed1f5,http://ufcstats.com/fighter-details/ea0ad15545...,L,SUBMISSION,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4acab67848e78327,http://ufcstats.com/fight-details/4acab67848e7...,SCOTT MORRIS,be9d259be012e8a4,http://ufcstats.com/fighter-details/be9d259be0...,W,SEAN DAUGHERTY,a683f9ddb70aa4bd,http://ufcstats.com/fighter-details/a683f9ddb7...,L,SUBMISSION,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [5]:
fight_df.info(show_counts=True, verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 8229 entries, 0adfc21045c02555 to 4acab67848e78327
Data columns (total 200 columns):
 #    Column             Non-Null Count  Dtype
---   ------             --------------  -----
 0    FIGHT_LINK         8229 non-null   object
 1    R_FIGHTER          8229 non-null   object
 2    R_FIGHTER_ID       8229 non-null   object
 3    R_FIGHTER_LINK     8229 non-null   object
 4    R_FIGHTER_RESULT   8229 non-null   object
 5    B_FIGHTER          8229 non-null   object
 6    B_FIGHTER_ID       8229 non-null   object
 7    B_FIGHTER_LINK     8229 non-null   object
 8    B_FIGHTER_RESULT   8229 non-null   object
 9    METHOD             8229 non-null   object
 10   ROUND              8229 non-null   object
 11   TIME               8229 non-null   object
 12   TIME FORMAT        8229 non-null   object
 13   REFEREE            8203 non-null   object
 14   DETAILS            8229 non-null   object
 15   WEIGHT_CLASS       8229 non-null   object
 16   TITLE_FIGHT        8229 non-null   bool
 17   PERF_BONUS         8229 non-null   bool
 18   R_KD_TOT           8229 non-null   object
 19   B_KD_TOT           8229 non-null   object
 20   R_ALL_STR_TOT      8229 non-null   object
 21   B_ALL_STR_TOT      8229 non-null   object
 22   R_TD_TOT           8229 non-null   object
 23   B_TD_TOT           8229 non-null   object
 24   R_TD_PCT_TOT       8229 non-null   object
 25   B_TD_PCT_TOT       8229 non-null   object
 26   R_SUB_ATT_TOT      8229 non-null   object
 27   B_SUB_ATT_TOT      8229 non-null   object
 28   R_REV_TOT          8229 non-null   object
 29   B_REV_TOT          8229 non-null   object
 30   R_CTRL_TOT         8229 non-null   object
 31   B_CTRL_TOT         8229 non-null   object
 32   R_KD_R1            8229 non-null   object
 33   B_KD_R1            8229 non-null   object
 34   R_ALL_STR_R1       8229 non-null   object
 35   B_ALL_STR_R1       8229 non-null   object
 36   R_TD_R1            8229 non-null   object
 37   B_TD_R1            8229 non-null   object
 38   R_TD_PCT_R1        8229 non-null   object
 39   B_TD_PCT_R1        8229 non-null   object
 40   R_SUB_ATT_R1       8229 non-null   object
 41   B_SUB_ATT_R1       8229 non-null   object
 42   R_REV_R1           8229 non-null   object
 43   B_REV_R1           8229 non-null   object
 44   R_CTRL_R1          8229 non-null   object
 45   B_CTRL_R1          8229 non-null   object
 46   R_SIG_STR_TOT      8229 non-null   object
 47   B_SIG_STR_TOT      8229 non-null   object
 48   R_SIG_STR_PCT_TOT  8229 non-null   object
 49   B_SIG_STR_PCT_TOT  8229 non-null   object
 50   R_HEAD_TOT         8229 non-null   object
 51   B_HEAD_TOT         8229 non-null   object
 52   R_BODY_TOT         8229 non-null   object
 53   B_BODY_TOT         8229 non-null   object
 54   R_LEG_TOT          8229 non-null   object
 55   B_LEG_TOT          8229 non-null   object
 56   R_DISTANCE_TOT     8229 non-null   object
 57   B_DISTANCE_TOT     8229 non-null   object
 58   R_CLINCH_TOT       8229 non-null   object
 59   B_CLINCH_TOT       8229 non-null   object
 60   R_GROUND_TOT       8229 non-null   object
 61   B_GROUND_TOT       8229 non-null   object
 62   R_SIG_STR_R1       8229 non-null   object
 63   B_SIG_STR_R1       8229 non-null   object
 64   R_SIG_STR_PCT_R1   8229 non-null   object
 65   B_SIG_STR_PCT_R1   8229 non-null   object
 66   R_HEAD_R1          8229 non-null   object
 67   B_HEAD_R1          8229 non-null   object
 68   R_BODY_R1          8229 non-null   object
 69   B_BODY_R1          8229 non-null   object
 70   R_LEG_R1           8229 non-null   object
 71   B_LEG_R1           8229 non-null   object
 72   R_DISTANCE_R1      8229 non-null   object
 73   B_DISTANCE_R1      8229 non-null   object
 74   R_CLINCH_R1        8229 non-null   object
 75   B_CLINCH_R1        8229 non-null   object
 76   R_GROUND_R1        8229 non-null   object
 77   B_GROUND_R1        8229 non-null   object
 78   R_KD_R2            5924 non-null   object
 79   B_KD_R2            5924 non-null   object
 80   R_ALL_STR_R2       5924 non-null   object
 81   B_ALL_STR_R2       5924 non-null   object
 82   R_TD_R2            5924 non-null   object
 83   B_TD_R2            5924 non-null   object
 84   R_TD_PCT_R2        5924 non-null   object
 85   B_TD_PCT_R2        5924 non-null   object
 86   R_SUB_ATT_R2       5924 non-null   object
 87   B_SUB_ATT_R2       5924 non-null   object
 88   R_REV_R2           5924 non-null   object
 89   B_REV_R2           5924 non-null   object
 90   R_CTRL_R2          5924 non-null   object
 91   B_CTRL_R2          5924 non-null   object
 92   R_KD_R3            4559 non-null   object
 93   B_KD_R3            4559 non-null   object
 94   R_ALL_STR_R3       4559 non-null   object
 95   B_ALL_STR_R3       4559 non-null   object
 96   R_TD_R3            4559 non-null   object
 97   B_TD_R3            4559 non-null   object
 98   R_TD_PCT_R3        4559 non-null   object
 99   B_TD_PCT_R3        4559 non-null   object
 100  R_SUB_ATT_R3       4559 non-null   object
 101  B_SUB_ATT_R3       4559 non-null   object
 102  R_REV_R3           4559 non-null   object
 103  B_REV_R3           4559 non-null   object
 104  R_CTRL_R3          4559 non-null   object
 105  B_CTRL_R3          4559 non-null   object
 106  R_SIG_STR_R2       5924 non-null   object
 107  B_SIG_STR_R2       5924 non-null   object
 108  R_SIG_STR_PCT_R2   5924 non-null   object
 109  B_SIG_STR_PCT_R2   5924 non-null   object
 110  R_HEAD_R2          5924 non-null   object
 111  B_HEAD_R2          5924 non-null   object
 112  R_BODY_R2          5924 non-null   object
 113  B_BODY_R2          5924 non-null   object
 114  R_LEG_R2           5924 non-null   object
 115  B_LEG_R2           5924 non-null   object
 116  R_DISTANCE_R2      5924 non-null   object
 117  B_DISTANCE_R2      5924 non-null   object
 118  R_CLINCH_R2        5924 non-null   object
 119  B_CLINCH_R2        5924 non-null   object
 120  R_GROUND_R2        5924 non-null   object
 121  B_GROUND_R2        5924 non-null   object
 122  R_SIG_STR_R3       4559 non-null   object
 123  B_SIG_STR_R3       4559 non-null   object
 124  R_SIG_STR_PCT_R3   4559 non-null   object
 125  B_SIG_STR_PCT_R3   4559 non-null   object
 126  R_HEAD_R3          4559 non-null   object
 127  B_HEAD_R3          4559 non-null   object
 128  R_BODY_R3          4559 non-null   object
 129  B_BODY_R3          4559 non-null   object
 130  R_LEG_R3           4559 non-null   object
 131  B_LEG_R3           4559 non-null   object
 132  R_DISTANCE_R3      4559 non-null   object
 133  B_DISTANCE_R3      4559 non-null   object
 134  R_CLINCH_R3        4559 non-null   object
 135  B_CLINCH_R3        4559 non-null   object
 136  R_GROUND_R3        4559 non-null   object
 137  B_GROUND_R3        4559 non-null   object
 138  EVENT_ID           8229 non-null   object
 139  DATE               8229 non-null   datetime64[ns]
 140  R_KD_R4            365 non-null    float64
 141  B_KD_R4            365 non-null    float64
 142  R_ALL_STR_R4       365 non-null    object
 143  B_ALL_STR_R4       365 non-null    object
 144  R_TD_R4            365 non-null    object
 145  B_TD_R4            365 non-null    object
 146  R_TD_PCT_R4        365 non-null    object
 147  B_TD_PCT_R4        365 non-null    object
 148  R_SUB_ATT_R4       365 non-null    float64
 149  B_SUB_ATT_R4       365 non-null    float64
 150  R_REV_R4           365 non-null    float64
 151  B_REV_R4           365 non-null    float64
 152  R_CTRL_R4          365 non-null    object
 153  B_CTRL_R4          365 non-null    object
 154  R_KD_R5            317 non-null    float64
 155  B_KD_R5            317 non-null    float64
 156  R_ALL_STR_R5       317 non-null    object
 157  B_ALL_STR_R5       317 non-null    object
 158  R_TD_R5            317 non-null    object
 159  B_TD_R5            317 non-null    object
 160  R_TD_PCT_R5        317 non-null    object
 161  B_TD_PCT_R5        317 non-null    object
 162  R_SUB_ATT_R5       317 non-null    float64
 163  B_SUB_ATT_R5       317 non-null    float64
 164  R_REV_R5           317 non-null    float64
 165  B_REV_R5           317 non-null    float64
 166  R_CTRL_R5          317 non-null    object
 167  B_CTRL_R5          317 non-null    object
 168  R_SIG_STR_R4       365 non-null    object
 169  B_SIG_STR_R4       365 non-null    object
 170  R_SIG_STR_PCT_R4   365 non-null    object
 171  B_SIG_STR_PCT_R4   365 non-null    object
 172  R_HEAD_R4          365 non-null    object
 173  B_HEAD_R4          365 non-null    object
 174  R_BODY_R4          365 non-null    object
 175  B_BODY_R4          365 non-null    object
 176  R_LEG_R4           365 non-null    object
 177  B_LEG_R4           365 non-null    object
 178  R_DISTANCE_R4      365 non-null    object
 179  B_DISTANCE_R4      365 non-null    object
 180  R_CLINCH_R4        365 non-null    object
 181  B_CLINCH_R4        365 non-null    object
 182  R_GROUND_R4        365 non-null    object
 183  B_GROUND_R4        365 non-null    object
 184  R_SIG_STR_R5       317 non-null    object
 185  B_SIG_STR_R5       317 non-null    object
 186  R_SIG_STR_PCT_R5   317 non-null    object
 187  B_SIG_STR_PCT_R5   317 non-null    object
 188  R_HEAD_R5          317 non-null    object
 189  B_HEAD_R5          317 non-null    object
 190  R_BODY_R5          317 non-null    object
 191  B_BODY_R5          317 non-null    object
 192  R_LEG_R5           317 non-null    object
 193  B_LEG_R5           317 non-null    object
 194  R_DISTANCE_R5      317 non-null    object
 195  B_DISTANCE_R5      317 non-null    object
 196  R_CLINCH_R5        317 non-null    object
 197  B_CLINCH_R5        317 non-null    object
 198  R_GROUND_R5        317 non-null    object
 199  B_GROUND_R5        317 non-null    object
dtypes: bool(2), datetime64[ns](1), float64(12), object(185)
memory usage: 12.8+ MB