todo/ideas/notes:
- add general parameterized load_if_exists function to utils to replace data loading functions in scrapers
- add conditional update handling/loading from local data for fighter data
- fighter stats with no data are recorded as "0" online, care
- derived fighter columns for
    - win streaks
    - ufc record
    - total record
    - champion/former champ status
- only pulling weight from fight data, not fighter data to account for people moving around divisions
    - would be nice to list all weights competed at/have missed weight marks, but weigh in weight isn't present on ufcstats
- reorg scraper class so that it makes more sense as a data entry point.

- including w/l/d/nc data for fighter biography, but take care using it
    - if used in training data, you really want their record at the time of the fight, not current
    - might be able to reverse engineer that from the fight data by counting their ufc fights, but this logic would mess up if there were gaps in someones ufc stint (eg fights in ufc, fights in other org, then fights back in ufc)

In [1]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

# IMMEDIATELY CHANGE TO ROOT DIR
# ONLY RUN THIS ONCE/INCLUDED CODE TO RESTART KERNEL ON EXECUTE.
# POSSIBLY ONLY USE THIS CONTEXT MANAGER
import os
os.chdir('..')
print(os.getcwd())

# local imports once you're in the root
from src.ufctools.scraping import FightDataScraper

d:\code\frankie_edgar_stan_zone

In [4]:
scraper = FightDataScraper()

Pulling event data from http://ufcstats.com/statistics/events/completed?page=all
Reading local event data from d:\code\frankie_edgar_stan_zone\data\event_data.csv
No new events, local data up to date
Loading local fight links from d:\code\frankie_edgar_stan_zone\data\fight_links.pickle
Reading local raw fight data from d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Reading local fighter data from d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

In [6]:
# data scraped as of 6/26
scraper.scrape_new_fights()

Checking for new events to scrape
No new event links to scrape.
Scraping fights from 4 event/s.

0it [00:00, ?it/s]

Updating fight data.
Saving fight data to d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Removing temporary files

,FIGHT_LINK,R_FIGHTER,R_FIGHTER_ID,R_FIGHTER_LINK,R_FIGHTER_RESULT,B_FIGHTER,B_FIGHTER_ID,B_FIGHTER_LINK,B_FIGHTER_RESULT,METHOD,...,R_LEG_R5,B_LEG_R5,R_DISTANCE_R5,B_DISTANCE_R5,R_CLINCH_R5,B_CLINCH_R5,R_GROUND_R5,B_GROUND_R5,EVENT_ID,DATE
FIGHT_ID,,,,,,,,,,,,,,,,,,,,,
03bc32bdb5a33496,http://ufcstats.com/fight-details/03bc32bdb5a3...,JAMAHAL HILL,5444c5a201d3ee5a,http://ufcstats.com/fighter-details/5444c5a201...,L,KHALIL ROUNTREE JR.,749f572d1d3161fb,http://ufcstats.com/fighter-details/749f572d1d...,W,DECISION - UNANIMOUS,...,3 of 3,5 of 5,26 of 56,37 of 57,0 of 0,0 of 0,0 of 0,0 of 0,400c7b43c86d27d3,2025-06-21
a1afc16e21d1a807,http://ufcstats.com/fight-details/a1afc16e21d1...,RAFAEL FIZIEV,c814b4c899793af6,http://ufcstats.com/fighter-details/c814b4c899...,W,IGNACIO BAHAMONDES,e4a47b07044ddd72,http://ufcstats.com/fighter-details/e4a47b0704...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
8e5744c664fec3e9,http://ufcstats.com/fight-details/8e5744c664fe...,CURTIS BLAYDES,fa6796c55d6c5440,http://ufcstats.com/fighter-details/fa6796c55d...,W,RIZVAN KUNIEV,739fd4fbb5d862f4,http://ufcstats.com/fighter-details/739fd4fbb5...,L,DECISION - SPLIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
36ec204f47e4d613,http://ufcstats.com/fight-details/36ec204f47e4...,TOFIQ MUSAYEV,ae81a3ac7b260411,http://ufcstats.com/fighter-details/ae81a3ac7b...,L,MYKTYBEK OROLBAI,bf2c8e01b07d3eb1,http://ufcstats.com/fighter-details/bf2c8e01b0...,W,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
7513a00037094075,http://ufcstats.com/fight-details/7513a0003709...,NAZIM SADYKHOV,ff62013d2fce6d13,http://ufcstats.com/fighter-details/ff62013d2f...,W,NIKOLAS MOTTA,37f560436d745c18,http://ufcstats.com/fighter-details/37f560436d...,L,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
19764211af05674c,http://ufcstats.com/fight-details/19764211af05...,MUHAMMAD NAIMOV,8d11d9c13e2ccdf7,http://ufcstats.com/fighter-details/8d11d9c13e...,W,BOGDAN GRAD,fb37795db81f93f3,http://ufcstats.com/fighter-details/fb37795db8...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
e512b80bbaea36c2,http://ufcstats.com/fight-details/e512b80bbaea...,SEOKHYEON KO,4a07b1988477502c,http://ufcstats.com/fighter-details/4a07b19884...,W,OBAN ELLIOTT,6b56e94a59b7b134,http://ufcstats.com/fighter-details/6b56e94a59...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
5fcf18bcd2a020f1,http://ufcstats.com/fight-details/5fcf18bcd2a0...,ISMAIL NAURDIEV,6a96ad1bc34fb113,http://ufcstats.com/fighter-details/6a96ad1bc3...,L,JUNYONG PARK,285ae0b4a68221f4,http://ufcstats.com/fighter-details/285ae0b4a6...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
fff3218758c513b8,http://ufcstats.com/fight-details/fff3218758c5...,DARIA ZHELEZNIAKOVA,07047eb7d17fb0a2,http://ufcstats.com/fighter-details/07047eb7d1...,W,MELISSA MULLINS,bd532e9a2b93870c,http://ufcstats.com/fighter-details/bd532e9a2b...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
2bfc0212f2cae65b,http://ufcstats.com/fight-details/2bfc0212f2ca...,IRINA ALEKSEEVA,103e2e33a60683e1,http://ufcstats.com/fighter-details/103e2e33a6...,L,KLAUDIA SYGULA,9f5e3c20ce40b344,http://ufcstats.com/fighter-details/9f5e3c20ce...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
8c140756bf43dcc2,http://ufcstats.com/fight-details/8c140756bf43...,TAGIR ULANBEKOV,f00ac08ab056af5d,http://ufcstats.com/fighter-details/f00ac08ab0...,W,AZAT MAKSUM,7f1bf0c255ec8756,http://ufcstats.com/fighter-details/7f1bf0c255...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
a12d3a6c8aaf87ca,http://ufcstats.com/fight-details/a12d3a6c8aaf...,HAMDY ABDELWAHAB,3329d692aea4dc28,http://ufcstats.com/fighter-details/3329d692ae...,L,MOHAMMED USMAN,da7f113b5ea39c43,http://ufcstats.com/fighter-details/da7f113b5e...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400c7b43c86d27d3,2025-06-21
d75b3d3c2b209b75,http://ufcstats.com/fight-details/d75b3d3c2b20...,KAMARU USMAN,f1b2aa7853d1ed6e,http://ufcstats.com/fighter-details/f1b2aa7853...,W,JOAQUIN BUCKLEY,b9437600497350f3,http://ufcstats.com/fighter-details/b943760049...,L,DECISION - UNANIMOUS,...,0 of 0,0 of 0,9 of 24,19 of 56,1 of 2,1 of 2,0 of 0,0 of 0,de277a4abcfeea46,2025-06-14
79dfbbdd14fbbd11,http://ufcstats.com/fight-details/79dfbbdd14fb...,ROSE NAMAJUNAS,47b63240018d5d86,http://ufcstats.com/fighter-details/47b6324001...,W,MIRANDA MAVERICK,f29a6350c69f4a33,http://ufcstats.com/fighter-details/f29a6350c6...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
e5bd7e6e2a50a843,http://ufcstats.com/fight-details/e5bd7e6e2a50...,EDMEN SHAHBAZYAN,4144798612ef96e5,http://ufcstats.com/fighter-details/4144798612...,W,ANDRE PETROSKI,5f61780fe5e9b6d0,http://ufcstats.com/fighter-details/5f61780fe5...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
1714950933f88ab9,http://ufcstats.com/fight-details/1714950933f8...,CODY GARBRANDT,d8c7c61b176e3994,http://ufcstats.com/fighter-details/d8c7c61b17...,L,RAONI BARCELOS,b9f28e7045fdfce7,http://ufcstats.com/fighter-details/b9f28e7045...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
08c04f18b0f58d71,http://ufcstats.com/fight-details/08c04f18b0f5...,MANSUR ABDUL-MALIK,841695e02c99a521,http://ufcstats.com/fighter-details/841695e02c...,W,CODY BRUNDAGE,f14f644d41ade29f,http://ufcstats.com/fighter-details/f14f644d41...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
ec2034b134ae71cd,http://ufcstats.com/fight-details/ec2034b134ae...,ALONZO MENIFIELD,a495f599e787614f,http://ufcstats.com/fighter-details/a495f599e7...,W,OUMAR SY,46e2011d92463b7e,http://ufcstats.com/fighter-details/46e2011d92...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
13e2ff8b3a122094,http://ufcstats.com/fight-details/13e2ff8b3a12...,PAUL CRAIG,eabf206b162b3b83,http://ufcstats.com/fighter-details/eabf206b16...,NC,RODOLFO BELLATO,69898645d600abdb,http://ufcstats.com/fighter-details/69898645d6...,NC,COULD NOT CONTINUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
e861e9cc0118c670,http://ufcstats.com/fight-details/e861e9cc0118...,MICHAEL CHIESA,c58f51dedb310998,http://ufcstats.com/fighter-details/c58f51dedb...,W,COURT MCGEE,523fa774700d7d3f,http://ufcstats.com/fighter-details/523fa77470...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
f6454f2e508626ec,http://ufcstats.com/fight-details/f6454f2e5086...,MALCOLM WELLMAKER,2e45d08b3f2f02c8,http://ufcstats.com/fighter-details/2e45d08b3f...,W,KRIS MOUTINHO,9c27f3217891f3f0,http://ufcstats.com/fighter-details/9c27f32178...,L,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
b39b8ff0d7de211a,http://ufcstats.com/fight-details/b39b8ff0d7de...,CODY DURDEN,7f6ed67d3ed3c036,http://ufcstats.com/fighter-details/7f6ed67d3e...,L,JOSE OCHOA,88be62d6c1e6dadb,http://ufcstats.com/fighter-details/88be62d6c1...,W,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
59c4fdb3c0673066,http://ufcstats.com/fight-details/59c4fdb3c067...,RICKY SIMON,5987b2458f4b5290,http://ufcstats.com/fighter-details/5987b2458f...,W,CAMERON SMOTHERMAN,5c84f673b7bb7c15,http://ufcstats.com/fighter-details/5c84f673b7...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
2ae7404681deb3b3,http://ufcstats.com/fight-details/2ae7404681de...,PHIL ROWE,8e382b585a92affe,http://ufcstats.com/fighter-details/8e382b585a...,W,ANGE LOOSA,1497e735d9f2560a,http://ufcstats.com/fighter-details/1497e735d9...,L,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
ab325ea526824723,http://ufcstats.com/fight-details/ab325ea52682...,JAMEY-LYN HORTH,5c637af9472ae7cc,http://ufcstats.com/fighter-details/5c637af947...,W,VANESSA DEMOPOULOS,2c483cf443f38ece,http://ufcstats.com/fighter-details/2c483cf443...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de277a4abcfeea46,2025-06-14
e61d83e4e1f9c4d7,http://ufcstats.com/fight-details/e61d83e4e1f9...,MERAB DVALISHVILI,c03520b5c88ed6b4,http://ufcstats.com/fighter-details/c03520b5c8...,W,SEAN O'MALLEY,b50a426a33da0012,http://ufcstats.com/fighter-details/b50a426a33...,L,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
81b84b34f0357fa5,http://ufcstats.com/fight-details/81b84b34f035...,JULIANNA PENA,3253b16d38ae087d,http://ufcstats.com/fighter-details/3253b16d38...,L,KAYLA HARRISON,1af1170ed937cba7,http://ufcstats.com/fighter-details/1af1170ed9...,W,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
e28e829800466aca,http://ufcstats.com/fight-details/e28e82980046...,KELVIN GASTELUM,8c0580d4fff106c1,http://ufcstats.com/fighter-details/8c0580d4ff...,L,JOE PYFER,c1085e1701b13eca,http://ufcstats.com/fighter-details/c1085e1701...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
df5dac45fc585fb0,http://ufcstats.com/fight-details/df5dac45fc58...,MARIO BAUTISTA,bc711b6dd95c1af6,http://ufcstats.com/fighter-details/bc711b6dd9...,W,PATCHY MIX,2cfba6c837c03ed0,http://ufcstats.com/fighter-details/2cfba6c837...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
2129acab2280bd29,http://ufcstats.com/fight-details/2129acab2280...,VICENTE LUQUE,6d4b63c767106d3a,http://ufcstats.com/fighter-details/6d4b63c767...,L,KEVIN HOLLAND,3a46b268013afede,http://ufcstats.com/fighter-details/3a46b26801...,W,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
b6a87389bdc36a00,http://ufcstats.com/fight-details/b6a87389bdc3...,BRUNO SILVA,294aa73dbf37d281,http://ufcstats.com/fighter-details/294aa73dbf...,L,JOSHUA VAN,17e97649403ba428,http://ufcstats.com/fighter-details/17e9764940...,W,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
01100a90b584215d,http://ufcstats.com/fight-details/01100a90b584...,AZAMAT MURZAKANOV,e90a2f22417af68e,http://ufcstats.com/fighter-details/e90a2f2241...,W,BRENDSON RIBEIRO,49edd0d90f60fb7d,http://ufcstats.com/fighter-details/49edd0d90f...,L,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
ac977a0389682124,http://ufcstats.com/fight-details/ac977a038968...,SERGHEI SPIVAC,e2f6b2769aaedd6c,http://ufcstats.com/fighter-details/e2f6b2769a...,L,WALDO CORTES-ACOSTA,fc08099550072fe4,http://ufcstats.com/fighter-details/fc08099550...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
f0488a4486a64af0,http://ufcstats.com/fight-details/f0488a4486a6...,KHAOS WILLIAMS,2558ae2e5671e318,http://ufcstats.com/fighter-details/2558ae2e56...,L,ANDREAS GUSTAFSSON,2caf993f53541fa1,http://ufcstats.com/fighter-details/2caf993f53...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
d078e9046aa86307,http://ufcstats.com/fight-details/d078e9046aa8...,ARIANE DA SILVA,6551c64fbcd1a467,http://ufcstats.com/fighter-details/6551c64fbc...,L,WANG CONG,2997e7fe3c9d3d4a,http://ufcstats.com/fighter-details/2997e7fe3c...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
9f4a0de31375ba04,http://ufcstats.com/fight-details/9f4a0de31375...,JEKA SARAGIH,57186c150c645200,http://ufcstats.com/fighter-details/57186c150c...,L,JOOSANG YOO,a44020ea2e8cd026,http://ufcstats.com/fighter-details/a44020ea2e...,W,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
2e4064e0e6d4d92e,http://ufcstats.com/fight-details/2e4064e0e6d4...,QUILLAN SALKILLD,17734443a833cdf7,http://ufcstats.com/fighter-details/17734443a8...,W,YANAL ASHMOUZ,c739c2995a275314,http://ufcstats.com/fighter-details/c739c2995a...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
0e8599eca8ccfa32,http://ufcstats.com/fight-details/0e8599eca8cc...,MARQUEL MEDEROS,e2be0c1a9b886d92,http://ufcstats.com/fighter-details/e2be0c1a9b...,W,MARK CHOINSKI,001eb2ab0f30e7ea,http://ufcstats.com/fighter-details/001eb2ab0f...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18c49685296c60e6,2025-06-07
212527d462690304,http://ufcstats.com/fight-details/212527d46269...,MATEUSZ GAMROT,72db2a14ffa73ece,http://ufcstats.com/fighter-details/72db2a14ff...,W,LUDOVIT KLEIN,5b86d491d63890c5,http://ufcstats.com/fighter-details/5b86d491d6...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
305d8c85b35a7d4e,http://ufcstats.com/fight-details/305d8c85b35a...,BILLY RAY GOFF,fa07345cc9db5cc9,http://ufcstats.com/fighter-details/fa07345cc9...,L,RAMIZ BRAHIMAJ,3d074044a33825e7,http://ufcstats.com/fighter-details/3d074044a3...,W,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
7aaa810540132a4b,http://ufcstats.com/fight-details/7aaa81054013...,DUSTIN JACOBY,e4277e87a789d687,http://ufcstats.com/fighter-details/e4277e87a7...,W,BRUNO LOPES,0abcf6bc47191219,http://ufcstats.com/fighter-details/0abcf6bc47...,L,KO/TKO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
106918bfbe24335d,http://ufcstats.com/fight-details/106918bfbe24...,KETLEN VIEIRA,b9706f80d005036c,http://ufcstats.com/fighter-details/b9706f80d0...,W,MACY CHIASSON,9cdd2da1a9104a0b,http://ufcstats.com/fighter-details/9cdd2da1a9...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
ad68450307a21ab1,http://ufcstats.com/fight-details/ad68450307a2...,ZACHARY REESE,23dec7c47cb418f8,http://ufcstats.com/fighter-details/23dec7c47c...,W,DUSKO TODOROVIC,866fd7b1a6c90e7f,http://ufcstats.com/fighter-details/866fd7b1a6...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
baa2ee0bf7f97079,http://ufcstats.com/fight-details/baa2ee0bf7f9...,JAFEL FILHO,65adf3856c4d9256,http://ufcstats.com/fighter-details/65adf3856c...,L,ALLAN NASCIMENTO,253076a23d03dcd0,http://ufcstats.com/fighter-details/253076a23d...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
2521fed000747f47,http://ufcstats.com/fight-details/2521fed00074...,KURT HOLOBAUGH,a7151778b3381036,http://ufcstats.com/fighter-details/a7151778b3...,L,JORDAN LEAVITT,ac026518a9b4dc0f,http://ufcstats.com/fighter-details/ac026518a9...,W,SUBMISSION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
ae89ba793121fe0c,http://ufcstats.com/fight-details/ae89ba793121...,BOLAJI OKI,4bdedbdeedff7d1d,http://ufcstats.com/fighter-details/4bdedbdeed...,W,MICHAEL ASWELL,01c9e4013afce141,http://ufcstats.com/fighter-details/01c9e4013a...,L,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31
73240bea13ed5e71,http://ufcstats.com/fight-details/73240bea13ed...,RAYANNE DOS SANTOS,02bb48869eb7ac8f,http://ufcstats.com/fighter-details/02bb48869e...,L,ALICE ARDELEAN,87f8699fdcc2c404,http://ufcstats.com/fighter-details/87f8699fdc...,W,DECISION - UNANIMOUS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a898bf9fb7710b3,2025-05-31

In [34]:
raw_fighter_df = scraper.fighter_data.copy()

In [32]:
raw_fighter_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2572 entries, 198994b47f395af0 to 1ad381c8994c4e5b
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FIGHTER_LINK  2572 non-null   object
 1   SCRAPE_DATE   2572 non-null   datetime64[ns]
 2   FIGHTER       2572 non-null   object
 3   WIN           2572 non-null   int64
 4   LOSS          2572 non-null   int64
 5   DRAW          2572 non-null   int64
 6   NC            2572 non-null   int64
 7   HEIGHT        2572 non-null   int64
 8   WEIGHT        2572 non-null   object
 9   REACH         2572 non-null   int64
 10  STANCE        2509 non-null   object
 11  DOB           2432 non-null   datetime64[ns]
 12  SLPM          2572 non-null   float64
 13  STR_ACC       2572 non-null   float64
 14  SAPM          2572 non-null   float64
 15  STR_DEF       2572 non-null   float64
 16  TD_AVG        2572 non-null   float64
 17  TD_ACC        2572 non-null   float64
 18  TD_DEF        2572 non-null   float64
 19  SUB_AVG       2572 non-null   float64
dtypes: datetime64[ns](2), float64(8), int64(6), object(4)
memory usage: 486.5+ KB

In [ ]:
# todo - local save

def process_fighter_data(raw_df, save_local=True, save_dest = PROCESSED_FIGHTER_DATA_PATH):
    # check for expected columns?

    # cols with percent strings
    pct_cols = ["STR_ACC", 'STR_DEF', 'TD_ACC', 'TD_DEF']

    raw_df['REACH'] = _parse_reach_col(raw_df['REACH'])
    raw_df['DOB'] = _parse_dob_col(raw_df['DOB'])
    raw_df['HEIGHT'] = _parse_height_col(raw_df['HEIGHT'])
    raw_df['WEIGHT'] = _parse_weight_col(raw_df['WEIGHT'])

    for col in pct_cols:
        raw_df[col]=_parse_pct_col(raw_df[col])

    return raw_df

In [35]:
process_fighter_data(raw_fighter_df)

,FIGHTER_LINK,SCRAPE_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
198994b47f395af0,http://ufcstats.com/fighter-details/198994b47f...,2025-05-30,CARLO PEDERSOLI JR.,11,3,0,0,71,170,75,SOUTHPAW,1993-06-08,4.17,0.37,4.12,0.61,2.91,0.44,0.00,0.0
73c7cfa551289285,http://ufcstats.com/fighter-details/73c7cfa551...,2025-05-30,BJ PENN,16,14,2,0,69,155,70,ORTHODOX,1978-12-13,2.76,0.48,3.20,0.56,1.19,0.55,0.74,0.5
d35298b6df168456,http://ufcstats.com/fighter-details/d35298b6df...,2025-05-30,TALITA ALENCAR,6,1,1,0,61,115,58,ORTHODOX,1990-10-17,2.62,0.33,3.77,0.53,2.50,0.20,0.50,0.2
1a1a4d7a29041d77,http://ufcstats.com/fighter-details/1a1a4d7a29...,2025-05-30,COLIN ROBINSON,10,12,0,0,76,243,0,ORTHODOX,1968-11-27,6.19,0.69,7.91,0.37,2.58,1.00,0.50,5.2
440c9dbab63528fb,http://ufcstats.com/fighter-details/440c9dbab6...,2025-05-30,PAUL HERRERA,1,1,0,0,70,185,0,ORTHODOX,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21b1132949f2a9b0,http://ufcstats.com/fighter-details/21b1132949...,2025-05-30,STEVE BERGER,21,23,2,1,71,170,0,ORTHODOX,1973-05-20,1.00,0.27,3.26,0.36,0.84,0.40,0.16,1.7
523af801b3429015,http://ufcstats.com/fighter-details/523af801b3...,2025-05-30,ALLAN ZUNIGA,13,1,0,0,67,155,70,ORTHODOX,1992-04-04,3.93,0.52,1.80,0.61,0.00,0.00,0.57,1.0
75f871836d41f90f,http://ufcstats.com/fighter-details/75f871836d...,2025-05-30,JUSTIN MCCULLY,11,5,2,0,73,225,73,ORTHODOX,1976-02-18,1.58,0.37,2.02,0.46,1.28,0.44,0.43,0.0
d661ce4da776fc20,http://ufcstats.com/fighter-details/d661ce4da7...,2025-05-30,PETR YAN,18,5,0,0,67,135,67,SWITCH,1993-02-11,5.11,0.54,4.13,0.58,1.61,0.49,0.84,0.1
1ad381c8994c4e5b,http://ufcstats.com/fighter-details/1ad381c899...,2025-05-30,BEN WALL,8,7,1,0,70,155,0,ORTHODOX,1989-03-25,1.47,0.29,8.53,0.29,0.00,0.00,1.00,0.0